# a_tensor_initialization

In [2]:
import torch

# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand

# (.to(), .cuda(), .cpu())를 이용해서 CPU와 GPU 간 데이터를 쉽게 이동할 수 있음
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

print("#" * 50, 1)

# torch.tensor function
# torch.tensor는 torch.Tesnsor와 다르게 전달된 데이터의 타입을 그대로 유지
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5 -> 사실상 바깥 괄호를 텐서의 차원으로 생각해도 될 듯
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2) -> 각 차원의 크기가 일정하지 않음
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])



torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

# b_tensor_initialization_copy

In [3]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1) # 복사

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # 복사가 아닌 참조

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


# c_tensor_initialization_constant_values

In [4]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3) # t3와 t3와 같은 크기와 데이터 타입을 가지는 텐서를 생성하며, 초기화되지 않은 임의의 값으로 채워짐
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print(t4)


tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([2.3694e-38, 1.8980e+01, 0.0000e+00, 0.0000e+00])
tensor([7.0065e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_valies

In [5]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2)) # low와 high 사이에 랜덤으로 size만큼의 텐서 생
print(t1)

t2 = torch.rand(size=(1, 3)) # 균등 분포에서 랜덤한 실수 값 생
print(t2)

t3 = torch.randn(size=(1, 3)) # 표준 정규분포에서 랜덤한 실를 생성함
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2)) # 주어진 평균과 표준편차를 가진 정규 분포에서 랜덤한 실수 값을 생성함
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3) # 균일한 간격의 숫자로 생
print(t5)

t6 = torch.arange(5) # torch.arange(stop): 0부터 stop 직전까지 정수 값을 차례대로 생성
print(t6)

print("#" * 30) 

torch.manual_seed(1729) # 난수 생성기 활용 난수가 패턴을 가
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[13, 14]])
tensor([[0.4028, 0.1042, 0.4498]])
tensor([[ 0.4688, -3.3226, -0.5417]])
tensor([[ 9.1087, 10.5772],
        [ 9.7159,  8.6629],
        [10.4033,  8.0837]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversions

In [6]:
import torch

# 뒤에 타입을 명시하면 해당 타입으로 텐서 생성

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


# f_tensor_operations

In [7]:
import torch

# 각 자리수 끼리 계산함

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm

In [8]:
import torch

# .dot -> 내적
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) # 행렬곱
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6) # 배치 행렬 곱
print(t7.size())


tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


# h_tensor_operations_matmul

In [9]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


# i_tensor_broadcasting

In [10]:
import torch

# 스탈라 텐서 
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

# 텐서 뺄셈과 브로드 캐스
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


# 텐서 정규화
def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

# 브로드 캐스팅은 텐서의 크기가 달라도 계산이 가능
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent #torch.rand(3, 2)가 (4, 3, 2)로 확장됨
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1 # t18이 (5, 3, 4, 1)로 확장됨
print((t17 + t18).size())

print("#" * 50, 6)

# 브로드캐스팅 규칙을 이용하여 서로 다른 크기의 텐서가 동일한 크기로 확장되어 연산
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

# 각 원소를 제곱함
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

# j_tensor_broadcasting

In [11]:
import torch

# 텐서 인덱싱 기본적으로 리스트 인덱싱이랑 유사한 듯

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_broadcasting

In [12]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2) # view는 텐서의 원소 수를 유지하며, 연속된 메모리를 필요
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6) # 메모리 레이아웃을 재조정하여 모양 변
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
# 스퀴즈는 크기가 1인 차원 제거  
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
#  첫 번째 차원(0번 차원)이 크기가 1일 때 제거  
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
# 차원 추가  
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
# 차원 펼치기 -> 다차원 배열을 1차원로
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

# 차원 순서 바꾸기  
# permute: 텐서의 차원 순서를 변경
# transpose: 두 차원 간 전치(swap)
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_broadcasting

In [13]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

# 텐서 결합
# 세 텐서의 두 번째 차원이 다르기 때문에, 두 번째 차원(dim=1)을 기준으로 결합
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

# 2차원 텐서간 병합: dim=0 (첫 번째 차원)에서 결합하면 행이 추가
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

# m_tensor_broadcasting

In [14]:
# torch.stack vs torch.cat
# stack**은 주어진 차원(dim)을 따라 새로운 차원을 추가
# cat은 기존 차원을 따라 텐서를 연결한 후 unsqueeze로 추가

import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

# stack과 cat을 dim=1에서 사용하면, 두 텐서가 각각 dim=1 위치에 추가
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# n_tensor_broadcasting

In [15]:
import torch

# torch.vstack: 수직 스택 
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

# 2차원 텐서를 수직으로 결합
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

# 3차원 텐서의 수직 스택
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

# 수평 스택
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

# 2차원 텐서의 수평 스택
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

# 3차원 텐서의 수평 스택
t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 기술적 취득과 고찰

In [ ]:
1. a_tensor_initialization
기술적 사항 취득:
첫 번째 코드 블록에서는 PyTorch에서 텐서를 초기화하는 다양한 방법을 배웠다. 
torch.Tensor와 torch.tensor의 차이점을 통해 데이터 타입을 어떻게 유지하거나 변경할 수 있는지 알 수 있었다. 
예를 들어, torch.Tensor([1, 2, 3])는 float32 데이터 타입으로 초기화되지만, torch.tensor([1, 2, 3])는 int64로 초기화된다는 점을 확인할 수 있었다.

고찰:
기본적인 텐서 생성 방법을 다룬 이 부분은 PyTorch로 작업할 때 꼭 필요한 기초 지식이다. 
텐서의 데이터 타입이 연산 성능과 정확도에 영향을 미칠 수 있기 때문에, 이를 적절히 다루는 방법을 습득하는 것이 중요하다.

2. b_tensor_initialization_copy
기술적 사항 취득:
이 코드 블록에서는 torch.Tensor(), torch.tensor(), torch.as_tensor()를 사용하여 텐서를 복사하거나 참조하는 방법을 배웠다. 
as_tensor()는 리스트나 배열을 참조하므로, 원본 데이터가 변경되면 참조된 텐서도 변경된다. 
반면, tensor()는 데이터를 복사하므로 원본 데이터의 변경이 텐서에 영향을 미치지 않는다.

고찰:
데이터 참조와 복사는 코드 효율성과 메모리 사용량에 큰 영향을 미친다. 
특히 대용량 데이터를 처리할 때 참조와 복사를 적절히 선택하는 것이 성능 최적화에 중요함을 알게 되었다.

3. c_tensor_initialization_constant_values)
기술적 사항 취득:
torch.ones()와 torch.zeros()를 사용하여 텐서를 상수값으로 초기화하는 방법을 학습했다. 
이외에도 torch.empty()를 사용해 임의의 값으로 초기화된 텐서를 생성할 수 있다는 점도 확인했다.

고찰:
특정 상황에서 1이나 0으로만 채워진 텐서가 필요할 때가 많은데, 이 함수들을 효율적으로 사용하면 간단하게 초기화할 수 있다.
또한 empty()로 생성된 텐서는 반드시 값을 채운 후 사용해야 한다는 점도 기억해야 한다.

4. d_tensor_initialization_random_values
기술적 사항 취득:
torch.randint(), torch.rand(), torch.randn() 등의 함수를 통해 랜덤한 값으로 텐서를 초기화할 수 있음을 배웠다. 
또한, torch.manual_seed()를 사용하면 랜덤한 값의 패턴을 재현할 수 있다는 점도 배웠다.

고찰:
딥러닝에서 랜덤하게 초기화된 값은 가중치 초기화에 사용되므로 매우 중요하다. 
또한, 실험 재현성을 보장하기 위해 manual_seed()를 적절히 활용하는 것이 필수적임을 깨달았다.

5. e_tensor_type_conversions
기술적 사항 취득:
dtype 인자를 사용하여 텐서의 데이터 타입을 명시적으로 설정하거나, to(), type() 메서드를 사용해 기존 텐서의 타입을 변환할 수 있음을 배웠다.

고찰:
텐서의 타입 변환은 메모리 최적화와 연산 속도에 직접적인 영향을 미친다. 
특히 고정 소수점이나 정수 타입으로 변환하는 경우, 메모리 사용량을 대폭 줄일 수 있어 큰 데이터를 다룰 때 유용하다.

6. f_tensor_operations
기술적 사항 취득:
덧셈, 뺄셈, 곱셈, 나눗셈과 같은 기본 연산을 텐서 간에 수행할 수 있음을 학습했다. 
각 연산은 자리 수가 일치하는 위치에 적용된다.

고찰:
텐서 간의 기본 연산은 신경망 학습에서 매우 빈번하게 사용되기 때문에 빠르고 정확하게 수행되어야 한다. 
PyTorch는 이러한 연산을 효율적으로 처리할 수 있도록 설계되어 있으며, 복잡한 연산도 간단하게 구현할 수 있었다.

7. g_tensor_operations_mm
기술적 사항 취득:
torch.dot() 및 torch.mm()를 사용한 행렬 곱 연산을 다루었다. 
특히 bmm()를 사용하여 배치 형태로 행렬 곱을 수행할 수 있음을 배웠다.

고찰:
행렬 곱은 딥러닝에서 매우 중요한 연산으로, 특히 다차원 데이터를 배치 단위로 처리할 때 효율성을 높일 수 있는 방법을 배웠다. 
연산 속도를 최적화하는 것이 모델 성능에 큰 영향을 미칠 수 있음을 깨달았다.

8. i_tensor_broadcasting
기술적 사항 취득:
브로드캐스팅을 통해 크기가 다른 텐서 간에도 연산을 수행할 수 있음을 배웠다. 
작은 크기의 텐서가 큰 크기의 텐서로 자동으로 확장되어 연산이 가능해진다.

고찰:
브로드캐스팅은 복잡한 연산을 단순화할 수 있는 매우 유용한 기능이다. 
이를 통해 더 적은 코드를 작성하면서도 유연하게 텐서 연산을 처리할 수 있다는 점을 알게 되었다.

9. k_tensor_broadcasting
기술적 사항 취득:
view(), reshape(), permute(), transpose() 등의 함수를 사용하여 텐서의 차원을 변경하거나 재배열하는 방법을 배웠다.

고찰:
데이터 전처리나 모델 입력으로 텐서를 사용할 때, 원하는 차원으로 변경하는 것이 매우 중요하다. 
특히 텐서의 차원을 변경하는 방법을 잘 이해하면 복잡한 네트워크 구조에서도 효율적으로 데이터를 처리할 수 있다.

9. l_tensor_concat
기술적 사항 취득:
다양한 차원을 가진 텐서들을 torch.cat()을 사용하여 결합하는 방법을 배웠다. 이 함수는 주어진 차원(axis) 기준으로 텐서들을 하나로 연결하는 기능을 한다. 예를 들어, 두 개의 텐서를 0번 차원을 기준으로 결합할 때 각각의 차원 크기가 일치해야 함을 이해하게 되었다.

고찰:
이 방법을 통해, 다차원 데이터를 처리할 때 각 차원에서 어떻게 데이터를 병합할지 고민할 수 있었다. 특히, 이미지 데이터나 시계열 데이터를 다루는 경우, 특정 차원에서의 결합을 통해 학습 데이터를 더욱 효율적으로 구성할 수 있음을 알게 되었다.

10. m_tensor_stacking
기술적 사항 취득:
torch.stack()을 사용하여 텐서들을 새로운 차원으로 스태킹하는 방법을 배웠다. 이 함수는 새로운 차원을 추가하여 여러 텐서를 한 번에 결합하는 방식으로 동작하며, 이는 torch.cat()과 달리 차원을 추가한다는 점에서 다르다.

고찰:
스태킹은 특히 배치(batch) 데이터나 이미지 데이터에서 여러 샘플을 쌓아 모델에 입력하기에 유용하다. 다차원 데이터를 다룰 때 차원을 명확히 구분하고 효율적으로 데이터를 준비하는 것이 중요하다는 점을 느꼈다.

11. n_tensor_vstack_hstack
기술적 사항 취득:
torch.vstack() 및 torch.hstack() 함수를 사용하여 각각 수직 및 수평으로 텐서를 결합하는 방법을 배웠다. 
vstack()은 텐서를 수직 방향으로 결합하고, hstack()은 수평 방향으로 결합한다.

고찰:
수직 및 수평 결합을 통해 이미지 또는 행렬 데이터를 직관적으로 결합할 수 있는 방법을 학습했다. 
특히, 데이터를 처리할 때 어느 방향으로 결합해야 하는지를 명확하게 이해하고, 이를 통해 모델에 맞는 형태로 데이터를 구성하는 것이 중요하다는 점을 깨달았다.

# 소감

In [ ]:
이번 과제를 통해 PyTorch의 기본적인 텐서 연산과 데이터 조작 방법을 깊이 있게 이해할 수 있었다. 
특히, 텐서를 다루는 다양한 기능들을 학습하며 PyTorch의 강력함을 다시 한 번 느꼈다. 
텐서의 초기화, 타입 변환, 브로드캐스팅, 텐서 연산 등은 딥러닝 모델을 구현하고 학습할 때 필수적인 요소들이며, 이러한 기술들을 이해하고 활용하는 것이 앞으로의 개발에 큰 도움이 될 것이다.

또한, 이번 과제를 통해 얻은 경험은 나중에 더 복잡한 모델을 설계하거나 디버깅할 때 매우 유용할 것으로 기대된다. 
다만, 일부 복잡한 함수들은 처음에는 이해하기 어려웠으나, 직접 코드를 작성하고 실행해 보면서 점차 익숙해졌다.

마지막으로, 향후 과제를 진행할 때는 다양한 실제 데이터를 활용하여 더 많은 실습을 해보고 싶다.